dist: trusty
sudo: required
language: csharp
solution: BorderEast.ArangoDB.Client.sln
mono: none
dotnet: 1.0.1
script:
  - cd ./src/BorderEast.ArangoDB.Client/BorderEast.ArangoDB.Client
  - dotnet restore
  - dotnet build
